### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by alokmenghrajani** [square/keywhiz-fs#12]
- `go get github.com/square/keywhiz-fs`
- http://osxfuse.github.io/ for building on mac os X.

**Comment by mcpherrinm** [comment]
First point: We need to write down to install you run "go get github.com/square/keywhiz-fs/..." and then you've got a $GOPATH/bin/keywhizfs binary that results.  We shouldn't expect people to know Go idioms to build our stuff.

**Comment by alokmenghrajani** [comment]
Document that cross compiling results in `Error resolving gid for : user: unknown user`
