### ISSUE TITLE
Fix Dockerfile to use glide for vendoring

### ISSUE THREAD

**Issue by deinspanjer** [square/keywhiz-fs#60]
I'm trying to build the docker daemon and getting this error.
I looked at the call in main.go and it has the following signature:

```
return sqmetrics.NewMetrics(*metricsURL, prefix, metrics.DefaultRegistry)
```

But https://github.com/square/go-sq-metrics/blob/master/metrics.go shows the following definition:

```
func NewMetrics(metricsURL, metricsPrefix string, interval time.Duration, registry metrics.Registry) *SquareMetrics {
```

There aren't any docs in either project to indicate whether it is used or how, but using git blame, I can see that the new parameter was added a week ago in https://github.com/square/go-sq-metrics/commit/d2f04d2afd8fcc82df032a9c70f5db6bf4e3f3b9 by @csstaub.

Looks like this project just needs to be updated as well?

**Comment by csstaub** [comment]
We should fix the docker file to use glide for pulling in vendored libs.

**Comment by csstaub** [comment]
@deinspanjer thanks for catching this. #62 should fix it for now.
